### PR TITLE
Feature/gotest

### PR DESCRIPTION
**Pull request by drewwells**
This reworks tests to use standard `go test` tooling. The appengine test is currently an integration tests, but not hidden behind integration build flag.

I plan on continuing to rework things so integration tests don't require pulling data over the network. This requires a bit more work to make use of https://golang.org/pkg/net/http/httptest/#example_Server. I think this is a good start at simplifying the testing process.

This PR is based off #2 so that should be approved first before considering this PR.

### CODE REVIEW

**Comment by ainsleyc** [comment]
Thanks for the pull! Looks pretty good.

My intent was to have two groups of tests: a larger group of units tests which are run often while developing, and a small set of integration tests that are run more infrequently but actually call the API.

The primary reason I wanted to have tests against the API (despite slowness and flakiness) is so that in the future it would be easy to detect if the driver was no longer working for external reasons (like the api endpoint changed, or the query specification changed, etc).

Given that, I believe the current pull doesn't have a way to run just the unit tests. Thoughts?

**Comment by drewwells** [comment]
Go test only runs the previous unit tests. You need to pass go test -tags
integration to run the integration tests. Appengine tests also won't run
unless a build tag is specified but really would require calling go test
with the appengine build tool

**Comment by ainsleyc** [comment]
Huh, strange. When I run 'go test -v' I get the following output, which seems to indicate both the unit and integration tests are being run. Is that not what you are getting?

=== RUN   TestComparisonFilter_MarshalJson_ShouldReturnJsonString
--- PASS: TestComparisonFilter_MarshalJson_ShouldReturnJsonString (0.00s)
=== RUN   TestLogicalFilter_MarshalJson_ShouldReturnJsonString
--- PASS: TestLogicalFilter_MarshalJson_ShouldReturnJsonString (0.00s)
=== RUN   TestGeoCircle_MarshalJson_ShouldReturnJsonString
--- PASS: TestGeoCircle_MarshalJson_ShouldReturnJsonString (0.00s)
=== RUN   TestGeoRect_MarshalJson_ShouldReturnJsonString
--- PASS: TestGeoRect_MarshalJson_ShouldReturnJsonString (0.00s)
=== RUN   TestGet_InvalidUrl_ShouldReturnError
--- PASS: TestGet_InvalidUrl_ShouldReturnError (0.00s)
=== RUN   TestGetClient_ShouldBeNull
--- PASS: TestGetClient_ShouldBeNull (0.00s)
=== RUN   TestGet_ConfigFile_ShouldExistAndBeValid
--- PASS: TestGet_ConfigFile_ShouldExistAndBeValid (0.00s)
=== RUN   TestGet_ReadWithQuery_ShouldReturnResults
=== RESULTS: 20 results for /t/places-us {"q":["starbucks"]}
--- PASS: TestGet_ReadWithQuery_ShouldReturnResults (4.83s)
=== RUN   TestGet_ReadWithKey_ShouldReturnResults
=== RESULTS: 20 results for /t/places-us {"KEY":["key"],"q":["starbucks"]}
--- PASS: TestGet_ReadWithKey_ShouldReturnResults (3.79s)
=== RUN   TestGet_ReadWithSingleComparisonFilter_ShouldReturnResults
=== RESULTS: 20 results for /t/places-us {"filters":["{\"name\":{\"$eq\":\"starbucks\"}}"]}
--- PASS: TestGet_ReadWithSingleComparisonFilter_ShouldReturnResults (0.12s)
=== RUN   TestGet_ReadWithLogicalFilter_ShouldReturnResults
=== RESULTS: 20 results for /t/places-us {"filters":["{\"$and\":[{\"name\":{\"$eq\":\"starbucks\"}},{\"locality\":{\"$eq\":\"new york\"}}]}"]}
--- PASS: TestGet_ReadWithLogicalFilter_ShouldReturnResults (0.03s)
=== RUN   TestGet_ReadWithGeoCircle_ShouldReturnResults
=== RESULTS: 20 results for /t/places-us {"geo":["{\"$circle\":{\"$center\":[34.06021,-118.41828],\"$meters\":50}}"]}
--- PASS: TestGet_ReadWithGeoCircle_ShouldReturnResults (0.05s)
=== RUN   TestGet_ReadWithGeoRect_ShouldReturnResults
=== RESULTS: 20 results for /t/places-us {"geo":["{\"$within\":{\"$rect\":[[34.0611,-118.42283],[34.05771,-118.41399]]}}"]}
--- PASS: TestGet_ReadWithGeoRect_ShouldReturnResults (0.06s)
...

**Comment by drewwells** [comment]
Ahh sorry, I seem to misunderstand how to apply multiple build tags. It was running the tests when integration was available or appengine wasn't passed. Can you try again? It should be fixed now:

```
-> % go test -v -run ConfigFile
PASS
ok  	github.com/ainsleyc/factual-go-driver	0.011s
```

**Comment by ainsleyc** [comment]
Awesome. Thanks again for the pull!

**Pull request merged**
