### PR TITLE
implement appengine http client and example

### LINKED ISSUE #1: appengine support
Appengine doesn't allow access to http.DefaultClient, so this driver fails to build on it. There appears to be some support for overriding the http.Client in go-oauth by making some low level.

This might be a good opportunity to switch to the semi-official oauth2 client https://github.com/golang/oauth2. What are your thoughts on this?

### PR DESCRIPTION
**Pull request by drewwells**
fixes #1

### CODE REVIEW

**Comment by ainsleyc** [comment]
Thanks for the pull! However it seems to be breaking one of the integration tests, would you mind having a look at that?

**Comment by drewwells** [comment]
The tests reference config.json but there isn't one in the repo that I see.
How do the tests work?

**Comment by drewwells** [comment]
That should fix the tests.

**Comment by ainsleyc** [comment]
Looks good. Thanks!

**Pull request merged**
